18/10 Track testing changes
QUT-Motorsport/QUTMS_Driverless pull request #328
Opened 2024-10-19 02:15 UTC by b1n-ch1kn

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [x] Optimisation

## [required] Description

Tested at track - working nominally, needs some improvements to speed control from Nav2

Merged features and refactors for testing.
- 2024 Clean and refactor
- EBS test nav
- SLAM cone detection

Tested at track - working nominally, needs some improvements to speed control from Nav2

Track testing tuning
- Nav2
- SLAM toolbox
- Planning
- Control

## [required] Documentation

Feature branch merges:
https://github.com/QUT-Motorsport/QUTMS_Driverless/pull/323
https://github.com/QUT-Motorsport/QUTMS_Driverless/pull/326
https://github.com/QUT-Motorsport/QUTMS_Driverless/pull/327

### [optional] Usability concerns or breaking changes?

See PRs for feature specific concerns.
Tuning fixes committed here affect visualisations - mapped cone markers now come from the topic output by gridmap to cone detection node, so the original topic out of the cone placement node is no longer being visualised.

2024-10-19 11:19 UTC, leungw16 requested changes

2024-10-19 11:19 UTC, leungw16 commented on src/navigation/odom_transformer/odom_transformer/node_odom_transformer.py
Wrong log message?

2024-10-20 04:17 UTC, b1n-ch1kn commented on src/navigation/odom_transformer/odom_transformer/node_odom_transformer.py
Good catch lol

2024-10-20 04:23 UTC, leungw16 approved these changes

2024-10-23 05:31 UTC, AlexCB192 approved these changes
lgtm

2024-10-23 05:32 UTC, merged